/*-------------------------------------------------------------------------------------------------
File Name : Ultrasonic.c
Author : Mostafa Elsayad
Date Created :
Description : source File for the AVR Ultrasonic Driver
--------------------------------------------------------------------------------------------------*/
#include "Ultrasonic.h"
#include "icu.h"
#include <util/delay.h>
/***********************************************GLOBAL VARIABLES***********************************************/
static uint16 g_echo_time =0;
/***********************************************FUNCTIONS DEFINITIONS***********************************************/
/*-------------------------------------------------------------------------------------------------------
Function Name : Ultrasonci_init
Description :
 Initialize the ICU driver as required.
 Setup the ICU call back function.
 Setup the direction for the trigger pin as output pin through the GPIO driver.
Args :
[in]
void
[Return]
void
--------------------------------------------------------------------------------------------------------*/
void Ultrasonic_init(void){
	Icu_ConfigType config={F_CPU_8,RISING};
	/*initialize icu  */
	Icu_init(&config);
	/*call back function */
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	/*set trigger as output pin*/
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT,ULTRASONIC_TRIGGER_PIN,PIN_OUTPUT);
    /*set echo as input pin */
	GPIO_setupPinDirection(ULTRASONIC_ECHO_PORT,ULTRASONIC_ECHO_PIN,PIN_INPUT);
	/*set trigger logic low*/
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT,ULTRASONIC_TRIGGER_PIN,LOGIC_LOW);
}
/*-------------------------------------------------------------------------------------------------------
Function Name : Ultrasonci_Trigger
Description :send the trigger pulse to ultrasonic
Args :
[in]
void
[Return]
void
--------------------------------------------------------------------------------------------------------*/
void Ultrasonic_Trigger(void){
	/*set trigger logic high*/
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN,LOGIC_HIGH);
    /*We need to transmit trigger pulse of at least 10 us to the HC-SR04 Trig Pin*/
	_delay_us(ULTRASONIC_TRIGGER_PULSE);
    /*set trigger logic low after capture pulse*/
    GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN,LOGIC_LOW);
}
/*-------------------------------------------------------------------------------------------------------
Function Name : Ultrasonci_readDistance
Description :
 Send the trigger pulse by using Ultrasonic_Trigger function.
 Start the measurements by the ICU from this moment.
Args :
[in]
void
[Return]
uint16
--------------------------------------------------------------------------------------------------------*/
uint16 Ultrasonic_readDistance(void){
	Ultrasonic_Trigger();
	/*distance =(time*0.017)*/
	return (g_echo_time*0.017);
}
/*-------------------------------------------------------------------------------------------------------
Function Name : Ultrasonci_edgeProcessing
Description :
This is the call back function called by the ICU driver.
This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
Args :
[in]
void
[Return]
void
--------------------------------------------------------------------------------------------------------*/
void Ultrasonic_edgeProcessing(void){
	static uint8 g_edgeCount = 0;
		g_edgeCount++;
		if(g_edgeCount == 1)
		{
			/*clear timer1*/
			Icu_clearTimerValue();
			/* Detect falling edge */
			Icu_setEdgeDetectionType(FALLING);
		}
		else if(g_edgeCount == 2)
		{

			/* capture the High time value */
			g_echo_time = Icu_getInputCaptureValue();
			/* Detect rising edge */
			Icu_setEdgeDetectionType(RISING);
			g_edgeCount=0;
		}
}
